server:
  port: 8080
spring:
  application:
    name: jpapitfalls
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/jpapitfalls
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update